name: Build TS-DART source code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-code:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 5
      matrix:
        python-version: ["3.9","3.10"]
        os: 
          - macOS-latest
          - ubuntu-latest
          - windows-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: Install required packages 
      run: |
        python -m pip install --upgrade pip
    - name: Pip install
      run: |
        python -m pip install .
        